#!/bin/sh

set -e

add_extension() {
  echo -n "Adding extension $1..."
  INSTDIR=`mktemp -d`
  /usr/lib/openoffice/program/unopkg add --shared $1 \
    "-env:UserInstallation=file:///$INSTDIR" \
    '-env:UNO_JAVA_JFW_INSTALL_DATA=$ORIGIN/../share/config/javasettingsunopkginstall.xml' \
    "-env:JFW_PLUGIN_DO_NOT_CHECK_ACCESSIBILITY=1"
  if [ -n $INSTDIR ]; then rm -rf $INSTDIR; fi
  echo " done."
}

if [ "$1" = "configure" -o "$1" = "upgrade" ]; then
	add_extension /usr/lib/openoffice/share/extension/install/voikko.oxt
fi

#DEBHELPER#
