.TH undocumented 1 2006-09-22 Malaga
.SH NAME
undocumented \- Malaga
.SH SYNOPSIS
\fBundocumented\fR
.SH DESCRIPTION
This program belongs to the Malaga, a system for automatic language analysis, 
but it does not have a useful manual page of its own. Please see the 
documentation under \fI/usr/share/doc/malaga-doc/\fR for more information.
