#!/bin/bash
#
# 	prerm - Configuration script for openoffice.org-voikko
#
#	by Teemu Likonen <tlikonen@iki.fi>
#
# This script removes language component(s) from OpenOffice.org's package
# manager.


# Names used in messages
NAME_STRONG=Oo2-voikko
NAME_WEAK=Oo2-voiko
OPENOFFICEORG=OpenOffice.org

# This package's name in Debian package manager. This is also the name of the
# directory the language component is in.
PACKAGE_NAME=openoffice.org-voikko

# The name of the language component
COMPONENT_BASENAME=oo2-voikko
COMPONENT_FULLPATH=/usr/lib/$PACKAGE_NAME/$COMPONENT_BASENAME-*.uno.pkg

# 'unopkg' registers and removes the language component to/from the
# OpenOffice.org. This is the full path name to it.
UNOPKG=/usr/lib/openoffice/program/unopkg


# Here we define a function that will display messages to user.

case "$(locale | grep ^LC_MESSAGES=)" in
	*fi_*) MSG_LANG=finnish ;;
	*) MSG_LANG="" ;;
esac

ICONV=""
which iconv &>/dev/null && ICONV="| iconv --from-code=UTF-8 --to-code=//TRANSLIT"

function msg() {
	case "$1" in
		upgrade_failed)
			case "$MSG_LANG" in
				finnish) echo VIRHE: prerm $2 $3
				;;
				*) echo ERROR: prerm $2 $3
				;;
			esac
		;;
		component_remove)
			case "$MSG_LANG" in
				finnish) eval cat <<EOF $ICONV
${NAME_STRONG} poistettu ${OPENOFFICEORG}ista.
EOF
				;;
				*) eval cat <<EOF $ICONV
${NAME_STRONG} removed from ${OPENOFFICEORG}.
EOF
				;;
			esac
		;;
		component_remove_failed)
			case "$MSG_LANG" in
				finnish) eval cat <<EOF $ICONV
VIRHE: ${NAME_WEAK}n poistaminen ${OPENOFFICEORG}ista epäonnistui.
EOF
				;;
				*) eval cat <<EOF $ICONV
ERROR: Failed to remove ${NAME_STRONG} from ${OPENOFFICEORG}.
EOF
				;;
			esac
		;;
		component_list_failed)
			case "$MSG_LANG" in
				finnish) eval cat <<EOF $ICONV
VIRHE: Mahdollisten aikaisemmin asennettujen ${OPENOFFICEORG}in
kielikomponenttien tarkistaminen epäonnistui.
EOF
				;;
				*) eval cat <<EOF $ICONV
ERROR: Failed to check previously installed ${OPENOFFICEORG} language
components.
EOF
				;;
			esac
		;;
	esac
}


### Copy these lines to form new message definitions #############
#		message)
#			case "$MSG_LANG" in
#				finnish) eval cat <<EOF $ICONV
#EOF
#				;;
#				*) eval cat <<EOF $ICONV
#EOF
#				;;
#			esac
#		;;
##################################################################




# If during the upgrade process the old prerm failed, dpkg will run this new
# package's prerm. No doubt this will fail too so we want to stop and leave the
# old package untouched.
if [ $1 = failed-upgrade ]
then
	msg upgrade_failed $1 $2
	exit 1
fi

# In case this script is run with sudo we set $HOME to /root so that regular
# user's $HOME doesn't get modified by root.
export HOME=/root

# We'll delete the lockfile too.
rm -f $HOME/.openoffice.org2/.lock



# We remove possible previously installed language component from the system.

if $UNOPKG list --shared &>/dev/null
then
	COMPONENT_LIST=$($UNOPKG list --shared 2>/dev/null | sed -ne "s/^Name: \\(${COMPONENT_BASENAME}.*\\)/\\1/p")
	for COMPONENT in $COMPONENT_LIST
	do
		if $UNOPKG remove --shared $COMPONENT &>/dev/null
		then msg component_remove
		else msg component_remove_failed
		fi
	done
else msg component_list_failed
fi

exit 0
