#!/bin/bash

# "wrapper" dpkg-buildpackage-ohjelmalle
#
# Kääntää uuden upstream-, downstream- tai arkkitehtuuriversion ja vaihtaa
# .changes-tiedostoon uuden distron. Tämä skripti täytyy ajaa
# lähdekoodihakemistossa, mutta itse kääntämistä varten luodaan
# väliaikaishakemisto eikä lähdekoodihakemistoon kosketa.


# Seuraavat asetukset voidaan määritellä $HOME/.hfrc-tiedostossa, jolloin niitä
# ei tarvitse antaa komentorivillä.

default_distribution=""			# Tämä distro laitetaan .changes-tiedostoon
default_key=""				# GPG-avain

[ -r $HOME/.hfrc ] && source $HOME/.hfrc


script_name=$(basename $0)
tmp_changes="../changes.tmp" # Älä laita tätä .changes-päätteiseksi.
action=$1
distribution=${2:-$default_distribution}
key=${3:-$default_key}
gpg_options="" ; [ $key ] && gpg_options="--default-key $key"
options="-i'.*debian/.*\.svn.*'"	# Lisäoptiot dpkg-buildpackagelle


# Kirjoitetaan uusi .changes-tiedosto entisen päälle.
function new_binary_changes() {
	changes=$(find .. -maxdepth 1 -name "*.changes" | grep -v '_source\.changes$' | sort | tail -n1)
	sed_command="s/^Distribution: .*$/Distribution: $distribution/"
	sed -e "$sed_command" $changes | gpg --clearsign $gpg_options >$tmp_changes
	[ -e $tmp_changes ] && mv $tmp_changes $changes && cat $changes
}

function new_source_changes() {
	changes=$(find .. -maxdepth 1 -name "*_source.changes" | sort | tail -n1)
	sed_command="s/^Distribution: .*$/Distribution: $distribution/"
	sed -e "$sed_command" $changes | gpg --clearsign $gpg_options >$tmp_changes
	[ -e $tmp_changes ] && mv $tmp_changes $changes && cat $changes
}

# .orig.tar.gz, .diff.gz, .deb
function up() {
	dpkg-buildpackage -sa -rfakeroot -k$key -uc $options && new_binary_changes
}

# .diff.gz, .deb
function down() {
	dpkg-buildpackage -sd -rfakeroot -k$key -uc $options && new_binary_changes
}

# .deb
function deb() {
	dpkg-buildpackage -sd -b -rfakeroot -k$key -uc $options && new_binary_changes
}

# Vain sorsat: .orig.tar.gz, diff.gz
function upsrc() {
	dpkg-buildpackage -sa -S -rfakeroot -k$key -uc $options && new_source_changes
}

# Vain sorsat: diff.gz
function downsrc() {
	dpkg-buildpackage -sd -S -rfakeroot -k$key -uc $options && new_source_changes
}

# Siivotaan käännöshakemisto
function clean() {
	fakeroot debian/rules clean
}


# Pääohjelma

if [[ ! $action || ! $distribution ]]; then
	action=""
	distribution=""
fi
case "$action" in
	up|down|deb|upsrc|downsrc|clean) $action ;;
	*)
		echo "Usage: $script_name action [distribution] [gpg_key]"
		echo "Where"
		echo "  action         is one of the following: up, down, deb, upsrc, downsrc or clean"
		echo "  distribution   is the target distribution. This must be set either in command line or in"
		echo "                 ~/.hfrc file. For example: default_distribution=unstable"
		echo "  gpg_key        GPG key used for signing .dsc and .changes files. This is optional and"
		echo "                 can be defined also in ~/.hfrc file: default_key=abcd1234"
		exit 1
	;;
esac
