#!/bin/bash
#
# A script to build Debian packages from Voikko's Git repository.
#
# Author: Teemu Likonen <tlikonen@iki.fi>
#
# This script is placed in the public domain.

component=$1
ref_src=${2:-HEAD}
ref_deb=${3:-HEAD}

make_url() {
	local component=$1
	local ref=$2
	printf 'https://github.com/voikko/%s/tarball/%s' "$component" "$ref"
}

debs() {
	local package not_installed
	local i=0
	for package in "$@"; do
		if ! dpkg --list "$package" 2>/dev/null | grep -q ^ii; then
			not_installed[i++]=$package
		fi
	done
	if [ "$not_installed" ]; then
		echo "ERROR: The following packages are required:"
		printf '  %s\n' "${not_installed[@]}"
		exit 1
	fi
}

quote_basic_re () {
	printf '%s\n' "$1" | sed -e 's,[][\^$.*],\\&,g'
}

quote_replace () {
	printf '%s\n' "$1" | sed -e 's,[\&],\\&,g'
}
	
quote_sh () {
	printf '%s\n' "$1" | sed -e 's,[][\*?],\\&,g'
}

get_remote() {
	# $1 = repository in Github
	# $2 = component's directory in the repository (if any)
	#      _with_ trailing slash
	# $3 = destination directory for extracting
	# $4 = The Git ref to download (branch, tag, commit reference...)
	local repo=$1
	local git_dir_re=$(quote_basic_re "$2")
	local git_dir_sh=$(quote_sh "$2")
	local dest_dir=$(quote_replace "$3")
	local ref=$4
	local url=$(make_url "$repo" "$ref")
	wget -O - -- "$url" | \
		tar --extract --gzip --wildcards \
		--no-wildcards-match-slash \
		--transform="s,[^/]*/${git_dir_re},$dest_dir/," \
		"*/${git_dir_sh}*"
}

update_changelog() {
	local source=$(dpkg-parsechangelog | awk '/^Source:/ {print $2}')
	local version=99.dev.$(date --utc +%Y%m%dT%H%M%SZ)
	local changelog_new=$(mktemp) || exit 1

	printf "%s (%s-1) unstable; urgency=low\n\n" \
		"$source" "$version" > "$changelog_new"
	printf "  * A development snapshot.\n\n" >> \
		"$changelog_new"
	printf " -- %s <%s>  %s\n\n" \
		"${DEBFULLNAME:-Nobody}" "${DEBEMAIL:-nobody@invalid}" \
		"$(date -R)" >> "$changelog_new"
	cat debian/changelog >> "$changelog_new"
	mv -f -- "$changelog_new" debian/changelog
}

build_deb() {
	dpkg-checkbuilddeps || exit 1
	fakeroot debian/rules clean || exit 1
	fakeroot debian/rules binary || exit 1
}

libvoikko() {
	local ref_src=${1:-HEAD}
	local ref_deb=${2:-HEAD}
	debs libtool automake
	get_remote corevoikko libvoikko/ libvoikko "$ref_src"
	get_remote debian-packages libvoikko+debian/ libvoikko/debian "$ref_deb"
	cd libvoikko || exit 1
	./autogen.sh || exit 1
	update_changelog
	build_deb
	echo
	dpkg-parsechangelog
}

mozvoikko() {
	local ref_src=${1:-HEAD}
	local ref_deb=${2:-HEAD}
	get_remote mozvoikko "" mozvoikko "$ref_src"
	get_remote debian-packages mozvoikko+debian/ mozvoikko/debian "$ref_deb"
	cd mozvoikko || exit 1
	update_changelog
	build_deb
	echo
	dpkg-parsechangelog
}

suomimalaga() {
	local ref_src=${1:-HEAD}
	local ref_deb=${2:-HEAD}
	get_remote corevoikko suomimalaga/ suomimalaga "$ref_src"
	get_remote debian-packages suomi-malaga+debian/ suomimalaga/debian \
		"$ref_deb"
	cd suomimalaga || exit 1
	update_changelog
	build_deb
	echo
	dpkg-parsechangelog
}

libreoffice-voikko () {
	local ref_src=${1:-HEAD}
	local ref_deb=${2:-HEAD}
	get_remote libreoffice-voikko "" libreoffice-voikko "$ref_src"
	get_remote debian-packages libreoffice-voikko+debian/ \
		libreoffice-voikko/debian "$ref_deb"
	cd libreoffice-voikko || exit 1
	update_changelog
	build_deb
	echo
	dpkg-parsechangelog
}

print_usage() {
	local name=$(basename -- "$0")
	cat <<EOF
$name - Debian build tool for Voikko components

Description: This tool obtains Voikko's source code from pre-defined
remote location and creates a ready-to-install .deb package from it. The
.deb package as well as the building directory is created under the
current directory.

Usage: $name <component> [source ref] [debian ref]

  <component>  = suomimalaga | libvoikko | libreoffice-voikko | mozvoikko

  [source ref] = A reference to the commit of the source code to be
                 downloaded. It must be a valid Git commit reference
                 (examples: branch, tag, 5af3d232, HEAD~4). The
                 default is HEAD.

  [debian ref] = Like above but a reference to the debian-packages
                 repository. The default is HEAD.

EOF
}

case "$component" in
libvoikko|libreoffice-voikko|suomimalaga|mozvoikko)
	debs build-essential fakeroot wget
	"$component" "$ref_src" "$ref_deb"
	;;
*)
	print_usage
	exit 2
	;;
esac
