#!/bin/bash
# Kääntää uuden upstream-, downstream- tai arkkitehtuuriversion ja vaihtaa
# .changes-tiedostoon uuden distron. Tämä skripti täytyy ajaa
# lähdekoodihakemistossa.

default_action=deb
default_key=e1ff97a0
default_distribution=dapper

script_name=$(basename $0)
tmp_changes="../tmp-changes" # Älä laita tätä .changes-päätteiseksi.

action=${1:-$default_action}
distribution=${2:-$default_distribution}
key=${3:-$default_key}


# Kirjoitetaan uusi .changes-tiedosto entisen päälle.
function modify_binary_changes() {
	package_name=$(basename $(pwd))
	find_pattern="${package_name}_*_*.changes"
	changes=$(find ../build-area -maxdepth 1 -name "$find_pattern" | grep -v '_source\.changes$' | sort | tail -n1)
	sed_command="s/^Distribution: .*$/Distribution: $distribution/"
	sed -e "$sed_command" $changes | gpg --clearsign --default-key=$key >$tmp_changes
	[ -e $tmp_changes ] && mv $tmp_changes $changes && cat $changes
}
function modify_source_changes() {
	package_name=$(basename $(pwd))
	find_pattern="${package_name}_*_source.changes"
	changes=$(find ../build-area -maxdepth 1 -name "$find_pattern" | sort | tail -n1)
	sed_command="s/^Distribution: .*$/Distribution: $distribution/"
	sed -e "$sed_command" $changes | gpg --clearsign --default-key=$key >$tmp_changes
	[ -e $tmp_changes ] && mv $tmp_changes $changes && cat $changes
}

# .orig.tar.gz, .diff.gz, .deb
function up() {
	svn-buildpackage -sa -rfakeroot -k$key -uc
	modify_binary_changes
}

# .diff.gz, .deb
function down() {
	svn-buildpackage -sd -rfakeroot -k$key -uc
	modify_binary_changes
}

# .deb
function deb() {
	svn-buildpackage -sd -b -rfakeroot -k$key -uc
	modify_binary_changes
}

# Vain sorsat: .orig.tar.gz, diff.gz
function upsrc() {
	svn-buildpackage -sa -S -rfakeroot -k$key -uc
	modify_source_changes
}

# Vain sorsat: diff.gz
function downsrc() {
	svn-buildpackage -sd -S -rfakeroot -k$key -uc
	modify_source_changes
}

# Siivotaan käännöshakemisto
function clean() {
	fakeroot debian/rules clean
}

case "$action" in
	up|down|deb|upsrc|downsrc|clean) $action ;;
	*)
		echo "Usage: $script_name [up|down|deb|upsrc|downsrc|clean] [distribution] [gpg key]"
		exit 1
	;;
esac
